pipeline{
    agent {
        label 'zepta'
    }
	
	environment {
            EMAIL_INFORM = 'abc@gmail.com;def@gmail.com;ghi@quillhash.com'
        }
    

    stages{

        stage('Pull Repo'){
            steps {
                checkout([$class: 'GitSCM',
                branches: [[name: '*/testing']],
                
                userRemoteConfigs: [[url: ' url here', 
                                credentialsId: 'Global ID']]])
            }
        }

        stage('Checking ports and all '){
            steps{
                script{
				
					Integer status = sh(script: 'sudo netstat -tnlp | grep 4000  >> /dev/null &&  echo 0 || echo 1 ', returnStdout: true)
                    Integer y =0
					
					
					println("x = " + x); 
                    
                    if ( status.equals(y) ){
                        sh "echo 'Port 4000 found in running condition '"
						
                    }
                }
            }
        }
    }
    
	post {
        failure {
          emailext(
            attachLog: true, attachmentsPattern: 'generatedFile.txt',
            subject: "${env.JOB_NAME} [${env.BUILD_NUMBER}] Jenkins Notification",
            body: """<p>'${env.JOB_NAME} [${env.BUILD_NUMBER}]' Jenkins FIle Script Fails":</p>
            <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
            to: "${EMAIL_INFORM}"
          )
        }
   }
        
}    
